version: '3.8'

services:
  lps-api:
    image: lps-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - lps-db

  lps-db:
    image: postgres
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  lps-pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "15432:80"
    depends_on:
      - lps-db

volumes:
  postgres:
