databases:
  - name: lps_db
    databaseName: property_app_1m6q
    user: property_app_1m6q_user

services:
  - type: web
    name: property_service
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lsp-app
          property: connectionString
      